=== astrobit/analysis_tools/share/genplots.dtd
<?xml version="1.0" encoding="utf-8"?>
<!ELEMENT GRAPH (COLOR*|AXIS*|	SOURCEFILE*|PLOT+|TEXT*)*>
<!ATTLIST GRAPH
	outputfile CDATA #REQUIRED
	title		CDATA #IMPLIED
	layout		(portrait|landscale|user) #IMPLIED
	size		(a4|letter|user) #IMPLIED
	width		CDATA #IMPLIED
	height		CDATA #IMPLIED
>
<!ELEMENT COLOR EMPTY>
<!ATTLIST COLOR
	name	CDATA #REQUIRED
	red		CDATA	#REQUIRED
	green	CDATA	#REQUIRED
	blue	CDATA	#REQUIRED
>
<!ELEMENT TEXT (#PCDATA)>
<!ATTLIST TEXT
	color	CDATA #IMPLIED
	width	CDATA #IMPLIED
	font	(times|helvetica|courier|symbol) #IMPLIED
	italics	(true|false) #IMPLIED
	bold	(true|false) #IMPLIED
	angle   CDATA #IMPLIED
	size    CDATA #IMPLIED
	xaxisid	CDATA #IMPLIED
	yaxisid CDATA #IMPLIED
	x		CDATA #REQUIRED
	y		CDATA #REQUIRED
>
<!ELEMENT PLOT (PLOTDATA?|PLOTFILE?)>
<!ATTLIST PLOT
	color	CDATA #IMPLIED
	style	(none|default|solid|sdash|ldash|lsdash|dot|sdashdot|ldashdot|lsdashdot) #IMPLIED
	width	CDATA #IMPLIED
	symbol	(none|default|square|circle|triup|tridn|trilt|trirt|diamond|times|plus|dash|asterisk|star4|star5|star6) #IMPLIED
	symbolsize CDATA #IMPLIED
	yoffset	CDATA #IMPLIED 
	xoffset CDATA #IMPLIED
	xaxisid	CDATA #IMPLIED
	yaxisid CDATA #IMPLIED
>
<!ELEMENT PLOTDATA (TUPLE*)>
<!ELEMENT TUPLE EMPTY>
<!ATTLIST TUPLE
	x	CDATA	#REQUIRED
	y	CDATA	#REQUIRED
>
<!ELEMENT PLOTFILE EMPTY>
<!ATTLIST PLOTFILE
	fileid	CDATA	#REQUIRED
	xcol	CDATA	#REQUIRED
	ycol	CDATA	#REQUIRED
>
<!ELEMENT SOURCEFILE EMPTY>
<!ATTLIST SOURCEFILE
	name	CDATA #REQUIRED
	fileid	ID	#REQUIRED
	separator	CDATA	#IMPLIED
	headerlines		CDATA	#REQUIRED
	wsseparated		(true|false)	#REQUIRED
	hasstrings		(true|false)	#IMPLIED
>
<!ELEMENT AXIS EMPTY>
<!ATTLIST AXIS
	title	CDATA	#IMPLIED
	axisid	ID		#REQUIRED
	log	(true|false) #IMPLIED
	invert (true|false) #IMPLIED
	direction (x|y) #REQUIRED
	min		CDATA	#IMPLIED
	max		CDATA	#IMPLIED
>

=== astrobit/analysis_tools/share/genplot_example.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE GRAPH SYSTEM "genplots.dtd">
<GRAPH outputfile="test.eps">
<SOURCEFILE name="genplot_example.csv" fileid="xyz" headerlines="1" wsseparated="false"/>
<PLOT color="red" width="4.0" style="ldash">
<PLOTDATA>
<TUPLE x="1" y="1"/>
<TUPLE x="2" y="4"/>
<TUPLE x="3" y="9"/>
<TUPLE x="4" y="16"/>
<TUPLE x="5" y="25"/>
<TUPLE x="6" y="36"/>
</PLOTDATA>
</PLOT>
<PLOT>
<PLOTFILE fileid="xyz" xcol="0" ycol="1"/>
</PLOT>
<PLOT>
<PLOTFILE fileid="xyz" xcol="0" ycol="1" style="sdash"/>
</PLOT>
<TEXT x="3" y="50" color="blue" width="2.0">example</TEXT>
</GRAPH>

=== astrobit/analysis_tools/share/genplot_example2.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE GRAPH SYSTEM "genplots.dtd">
<GRAPH outputfile="genplot_example2.eps">
<SOURCEFILE name="genplot_example.csv" fileid="xyz" headerlines="1" wsseparated="false"/>
<AXIS direction="x" axisid="xaxis1" log="true" displaymajorindices="true" displayminorindices="true" title="X-axis" min="0.9" max="10"/>
<AXIS direction="y" axisid="yaxis1" displaymajorindices="false" title="Y-axis" min="0" max="1000"/>
<AXIS direction="y" axisid="yaxis2" log="true" displaymajorindices="true" title="Y2-axis" min="0.1" max="1000"/>
<PLOT yaxisid="yaxis1" xaxisid="xaxis1" color="red" width="4.0" style="ldash">
<PLOTDATA>
<TUPLE x="1" y="1"/>
<TUPLE x="2" y="4"/>
<TUPLE x="3" y="9"/>
<TUPLE x="4" y="16"/>
<TUPLE x="5" y="25"/>
<TUPLE x="6" y="36"/>
</PLOTDATA>
</PLOT>
<PLOT yaxisid="yaxis1" xaxisid="xaxis1" >
<PLOTFILE fileid="xyz" xcol="0" ycol="1"/>
</PLOT>
<PLOT yaxisid="yaxis2" xaxisid="xaxis1" >
<PLOTFILE fileid="xyz" xcol="0" ycol="1"/>
</PLOT>
<TEXT xaxisid="xaxis1" yaxisid="yaxis1" x="3" y="50" color="blue" width="2.0">example</TEXT>
</GRAPH>
