=== astrobit/analysis_tools/share/specfit.dtd
<?xml version="1.0" encoding="utf-8"?>
<!ELEMENT SPECFIT (FIT+|MODELLIST*|DATAFILE*)*>

<!ELEMENT DATAFILE EMPTY>
<!ATTLIST DATAFILE
	filepath	CDATA	#REQUIRED
	id			ID		#REQUIRED
>

<!ELEMENT MODELLIST (MODEL)+>
<!ATTLIST MODELLIST
	id		ID #REQUIRED
>
<!ELEMENT MODEL EMPTY>
<!ATTLIST MODEL
	id				CDATA #REQUIRED
>
<!-- in FIT, the source is only optional if a non-json data file is specified -->
<!-- in FIT, the instrument is only optional if MJD is unique, otherwise required-->
<!-- in FIT, the ebv is the E(B-V) value for the SN to use for the dereddening routine.  The default value is 0 (spectrum will not be dereddened) -->
<!-- in FIT, the usejsonebv flag indicates to use a weighted E(B-V) value from the json data file. The default value is false - the user specified value in ebv will be used -->
<!ELEMENT FIT (MODEL*|SUGGESTPARAM?|MODLIST*)+>
<!ATTLIST FIT
	datafileid	IDREF #REQUIRED
	source		CDATA #IMPLIED
	mjd			CDATA #REQUIRED
	instrument	CDATA #IMPLIED
	feature		(CaNIR|CaHK|Si6355|O7777) #REQUIRED
	ebv			CDATA #IMPLIED
	usejsonebv	(true|false) #IMPLIED
>
<!ELEMENT MODLIST EMPTY>
<!ATTLIST MODLIST
	id	IDREF #REQUIRED
>
<!ELEMENT SUGGESTPARAM EMPTY>
<!ATTLIST SUGGESTPARAM
	ps_temp	CDATA	#IMPLIED
	ps_vel	CDATA #IMPLIED
	ejecta_temp	CDATA #IMPLIED
	shell_temp	CDATA #IMPLIED
	ejecta_log_S	CDATA	#IMPLIED
	shell_log_S		CDATA #IMPLIED
>

=== astrobit/analysis_tools/share/specfit_example.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE SPECFIT SYSTEM "specfit.dtd">
<SPECFIT>
<DATAFILE filepath="/home/astrobit/Downloads/SN2011fe.json" id="filea" />
<MODELLIST id="mass">
	<MODEL id="61"/>
	<MODEL id="57"/>
	<MODEL id="41"/>
	<MODEL id="49"/>
	<MODEL id="45"/>
	<MODEL id="53"/>
</MODELLIST>
<FIT source="21" mjd="55805.0" instrument="Gemini-N - GMOS" feature="CaNIR" datafileid="filea" >
	<MODLIST id="mass"/>
</FIT>	
<FIT source="21" mjd="55805.0" instrument="LRS2" feature="CaNIR" datafileid="filea" >
	<MODLIST id="mass"/>
</FIT>	
<FIT source="21" mjd="55813.0" instrument="LRS2" feature="CaNIR" datafileid="filea" >
	<MODLIST id="mass"/>
</FIT>	
<FIT source="21" mjd="52718.0" feature="CaNIR" datafileid="filea" >
	<MODLIST id="mass"/>
	<MODEL id="65"/>
</FIT>	
</SPECFIT>
